CREATE DATABASE NARPAVI_CUSTOMER_INFO;
USE NARPAVI_CUSTOMER_INFO;

DROP TABLE FINANCE_DETAILS;
DROP TABLE CUSTOMER_DETAILS;


CREATE TABLE CUSTOMER_DETAILS
(
CUSTOMER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50),
DOB DATE,
ADHAR_NUM VARCHAR(50),
RATION_CARD_NUM VARCHAR(20),
DRIVING_LICENSE_NUM VARCHAR(20),
VOTER_ID_NUM VARCHAR(20),
PASSPORT_NUMBER VARCHAR(20),
PAN_ID_NUM VARCHAR(20),
EMAIL VARCHAR(50),
CONTACT_NUM VARCHAR(30) NOT NULL,
ADDRESS_STREET VARCHAR(50),
ADDRESS_VILLAGE_OR_TOWN VARCHAR(50),
ADDRESS_CITY VARCHAR(50),
ADDRESS_ZIP VARCHAR(10),
ADDRESS_STATE VARCHAR(50),
ADDRESS_COUNTRY VARCHAR(50),
VEHICLE_NUMBER VARCHAR(20),
CUSTOMER_DETAILS_CLOB TEXT
);


CREATE TABLE FINANCE_DETAILS
(
FINANCE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
FINANCE_NAME VARCHAR(100) NOT NULL,
CUSTOMER_ID INT NOT NULL,
FINANCE_OWNER_NAME VARCHAR(100),
LOAN_STATUS VARCHAR(15),
COMMENTS_ABOUT_CUSTOMER VARCHAR(500),
DELINQUENCY_AMOUNT VARCHAR(10),
REPAYMENT_TYE VARCHAR(10),
FINANCE_DETAILS_CLOB TEXT,
FOREIGN KEY (CUSTOMER_ID)
      REFERENCES CUSTOMER_DETAILS(CUSTOMER_ID)
);

CREATE FULLTEXT INDEX CUSTOMER_DETAILS_INDEX
ON CUSTOMER_DETAILS(FIRST_NAME, LAST_NAME,ADHAR_NUM,RATION_CARD_NUM, DRIVING_LICENSE_NUM, VOTER_ID_NUM, PASSPORT_NUMBER,VEHICLE_NUMBER, EMAIL,CONTACT_NUM,ADDRESS_VILLAGE_OR_TOWN,ADDRESS_CITY,ADDRESS_ZIP,ADDRESS_STATE,ADDRESS_COUNTRY);
CREATE FULLTEXT INDEX FINANCE_DETAILS_INDEX
ON FINANCE_DETAILS(FINANCE_NAME, FINANCE_OWNER_NAME,LOAN_STATUS,COMMENTS_ABOUT_CUSTOMER,DELINQUENCY_AMOUNT,REPAYMENT_TYE);

select distinct CUSTOMER_ID, CUSTOMER_DETAILS_CLOB from (select C.CUSTOMER_ID as CUSTOMER_ID, C.CUSTOMER_DETAILS_CLOB as CUSTOMER_DETAILS_CLOB,
       		match(C.FIRST_NAME, C.LAST_NAME,C.ADHAR_NUM,C.RATION_CARD_NUM, C.DRIVING_LICENSE_NUM, C.VOTER_ID_NUM, C.PASSPORT_NUMBER,C.VEHICLE_NUMBER, C.EMAIL,CONTACT_NUM,
       		C.ADDRESS_VILLAGE_OR_TOWN,C.ADDRESS_CITY,C.ADDRESS_ZIP,C.ADDRESS_STATE,C.ADDRESS_COUNTRY) against ('0302*' IN BOOLEAN MODE) as t1_match,
        	match(F.FINANCE_NAME, F.FINANCE_OWNER_NAME,F.LOAN_STATUS,F.COMMENTS_ABOUT_CUSTOMER,F.DELINQUENCY_AMOUNT,F.REPAYMENT_TYE) against ('0302*' IN BOOLEAN MODE) as t2_match
    		from CUSTOMER_DETAILS C inner join FINANCE_DETAILS F on C.CUSTOMER_ID = F.CUSTOMER_ID  
			) as S where S.t1_match > 0 OR S.t2_match > 0
            
            
select * from FINANCE_DETAILS
===============================================================================================================








CREATE DATABASE DEV_MIND_FINANCE_KARMA;
USE DEV_MIND_FINANCE_KARMA;

DROP TABLE FINANCE_DETAILS;
DROP TABLE CUSTOMER_DETAILS;


CREATE TABLE CUSTOMER_DETAILS
(
CUSTOMER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50),
DOB DATE,
ADHAR_NUM VARCHAR(50),
RATION_CARD_NUM VARCHAR(20),
DRIVING_LICENSE_NUM VARCHAR(20),
VOTER_ID_NUM VARCHAR(20),
PASSPORT_NUMBER VARCHAR(20),
PAN_ID_NUM VARCHAR(20),
EMAIL VARCHAR(50),
CONTACT_NUM VARCHAR(30) NOT NULL,
ADDRESS_STREET VARCHAR(50),
ADDRESS_VILLAGE_OR_TOWN VARCHAR(50),
ADDRESS_CITY VARCHAR(50),
ADDRESS_ZIP VARCHAR(10),
ADDRESS_STATE VARCHAR(50),
ADDRESS_COUNTRY VARCHAR(50),
VEHICLE_NUMBER VARCHAR(20),
CUSTOMER_DETAILS_CLOB TEXT
);


CREATE TABLE FINANCE_DETAILS
(
FINANCE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
FINANCE_NAME VARCHAR(100) NOT NULL,
CUSTOMER_ID INT NOT NULL,
FINANCE_OWNER_NAME VARCHAR(100),
DELINQUENCY VARCHAR(3),
COMMENTS_ABOUT_CUSTOMER VARCHAR(500),
DELINQUENCY_AMOUNT VARCHAR(10),
REPAYMENT_TYE VARCHAR(10),
FINANCE_DETAILS_CLOB TEXT,
FOREIGN KEY (CUSTOMER_ID)
      REFERENCES CUSTOMER_DETAILS(CUSTOMER_ID)
);


DROP TABLE FINANCE_DETAILS;
CREATE TABLE FINANCE_DETAILS
(
FINANCE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
FINANCE_NAME VARCHAR(100) NOT NULL,
CUSTOMER_ID INT NOT NULL,
FINANCE_OWNER_NAME VARCHAR(100),
DELINQUENCY VARCHAR(3),
COMMENTS_ABOUT_CUSTOMER VARCHAR(500),
DELINQUENCY_AMOUNT VARCHAR(10),
REPAYMENT_TYE VARCHAR(10),
FINANCE_DETAILS_CLOB TEXT,
FOREIGN KEY (CUSTOMER_ID)
      REFERENCES CUSTOMER_DETAILS(CUSTOMER_ID)
);
ALTER TABLE CUSTOMER_DETAILS
DROP INDEX CUSTOMER_DETAILS_INDEX;

ALTER TABLE FINANCE_DETAILS
DROP INDEX FINANCE_DETAILS_INDEX;

CREATE FULLTEXT INDEX CUSTOMER_DETAILS_INDEX
ON CUSTOMER_DETAILS(FIRST_NAME, LAST_NAME,ADHAR_NUM,RATION_CARD_NUM, DRIVING_LICENSE_NUM, VOTER_ID_NUM, PASSPORT_NUMBER,VEHICLE_NUMBER, EMAIL,CONTACT_NUM,ADDRESS_VILLAGE_OR_TOWN,ADDRESS_CITY,ADDRESS_ZIP,ADDRESS_STATE,ADDRESS_COUNTRY);
CREATE FULLTEXT INDEX FINANCE_DETAILS_INDEX
ON FINANCE_DETAILS(FINANCE_NAME, FINANCE_OWNER_NAME,DELINQUENCY,COMMENTS_ABOUT_CUSTOMER,DELINQUENCY_AMOUNT,REPAYMENT_TYE);


select distinct CUSTOMER_ID, CUSTOMER_DETAILS_CLOB from (select C.CUSTOMER_ID as CUSTOMER_ID, C.CUSTOMER_DETAILS_CLOB as CUSTOMER_DETAILS_CLOB,
       		match(C.FIRST_NAME, C.LAST_NAME,C.ADHAR_NUM,C.RATION_CARD_NUM, C.DRIVING_LICENSE_NUM, C.VOTER_ID_NUM, C.PASSPORT_NUMBER,C.VEHICLE_NUMBER, C.EMAIL,CONTACT_NUM,
       		C.ADDRESS_VILLAGE_OR_TOWN,C.ADDRESS_CITY,C.ADDRESS_ZIP,C.ADDRESS_STATE,C.ADDRESS_COUNTRY) against ('0302*' IN BOOLEAN MODE) as t1_match,
        	match(F.FINANCE_NAME, F.FINANCE_OWNER_NAME,F.DELINQUENCY,F.COMMENTS_ABOUT_CUSTOMER,F.DELINQUENCY_AMOUNT,F.REPAYMENT_TYE) against ('0302*' IN BOOLEAN MODE) as t2_match
    		from CUSTOMER_DETAILS C inner join FINANCE_DETAILS F on C.CUSTOMER_ID = F.C.CUSTOMER_ID  
			) as S where S.t1_match > 0 OR S.t2_match > 0





=====================================================

CREATE DATABASE DEV_MIND_FINANCE_KARMA;
USE DEV_MIND_FINANCE_KARMA;

DROP TABLE FINANCE_KARMA_CUSTOMER_DETAILS;

CREATE TABLE CUSTOMER_DETAILS
(
CUSTOMER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
DOB DATE,
ADHAR_NUM VARCHAR(50),
EMAIL VARCHAR(50),
CONTACT_NUM VARCHAR(30) NOT NULL,
ADDRESS_STREET VARCHAR(50),
ADDRESS_VILLAGE_OR_TOWN VARCHAR(50),
ADDRESS_CITY VARCHAR(50),
ADDRESS_ZIP VARCHAR(10),
ADDRESS_STATE VARCHAR(50),
ADDRESS_COUNTRY VARCHAR(50),
CUSTOMER_DETAILS_CLOB TEXT

);

CREATE TABLE FINANCE_DETAILS
(
FINANCE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
FINANCE_NAME VARCHAR(100) NOT NULL,
CUSTOMER_ID INT NOT NULL,
FINANCE_OWNER_NAME VARCHAR(100),
DELINQUENCY VARCHAR(3),
DELINQUENCY_DETAILS VARCHAR(500),
DELINQUENCY_AMOUNT VARCHAR(10),
REPAYMENT_TYE VARCHAR(10)
FINANCE_DETAILS_CLOB TEXT,
FOREIGN KEY (CUSTOMER_ID)
      REFERENCES CUSTOMER_DETAILS(CUSTOMER_ID)
);

commit;